license_id: "cc-by-igo"
subnational: 1  # has to be 0 or 1
notes: ""
caveats: ""
methodology: "Registry"
dataset_source: "Chatham House"
package_creator: "mcarans"
private: False  # has to be True or False
